site_name: LaTeX Vorlagen
site_url: https://numpdes.github.io/thesis-template/
repo_url: https://github.com/NumPDEs/thesis-template
theme:
  name: material
  language: de
  icon: 
    logo: octicons/repo-template-24
  palette:
    # light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Wechsle zu dunklem Modus
    # dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Wechsle zu hellem Modus
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins: []
