name: Compile and package LaTeX project and deploy to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow for pushing to the repository
permissions:
  contents: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    strategy:
      matrix:
        type: [seminar, bachelor, diplom, diss]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      # Create ZIP archive of LaTeX project and upload as artifact
      - name: Rename all .type.tex files to .tex
        run: find . -name "*.${{ matrix.type }}.tex" -exec sh -c 'x="{}"; mv -- "$x" "${x%.${{ matrix.type }}.tex}.tex"' \;
      - name: Remove all left over .type.tex files
        run: find . -name "*.*.tex" -delete
      - name: Zip LaTeX project
        run: zip -r template_${{ matrix.type }}.zip * -x README.md
      - name: Upload LaTeX project as artifact
        uses: actions/upload-artifact@v4
        with:
          name: template_${{ matrix.type }}_zip
          path: template_${{ matrix.type }}.zip

      # Compile LaTeX document and upload as artifact
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
      - name: Rename PDF file
        run: mv main.pdf template_${{ matrix.type }}.pdf
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: template_${{ matrix.type }}_pdf
          path: template_${{ matrix.type }}.pdf

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create upload directory
        run: mkdir -p upload

      # Download artifacts
      - name: Download PDFs
        uses: actions/download-artifact@v4
        with:
          pattern: template_*_pdf
          path: upload/pdfs
          merge-multiple: true
      - name: Download LaTeX projects
        uses: actions/download-artifact@v4
        with:
          pattern: template_*_zip
          path: upload/dl
          merge-multiple: true

      # Push to gh-pages branch
      - name: Push contents of upload directory to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./upload
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
