name: Deploy documentation to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow for pushing to the repository
permissions:
  contents: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    strategy:
      matrix:
        type: [seminar, bachelor, diplom, diss]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      # Create ZIP archive of LaTeX project and upload as artifact
      - name: Rename template file to main.tex
        run: mv template_${{ matrix.type }}.tex main.tex
      - name: Zip LaTeX project
        run: zip -r template_${{ matrix.type }}.zip * -x docs\* template_*.tex
      - name: Upload LaTeX project as artifact
        uses: actions/upload-artifact@v4
        with:
          name: template_${{ matrix.type }}_zip
          path: template_${{ matrix.type }}.zip

      # Compile LaTeX document and upload as artifact
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            main.tex
      - name: Rename PDF file
        run: mv main.pdf template_${{ matrix.type }}.pdf
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: template_${{ matrix.type }}_pdf
          path: template_${{ matrix.type }}.pdf

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Download artifacts
      - name: Download PDFs
        uses: actions/download-artifact@v4
        with:
          pattern: template_*_pdf
          path: docs/pdfs
          merge-multiple: true
      - name: Download LaTeX projects
        uses: actions/download-artifact@v4
        with:
          pattern: template_*_zip
          path: docs/dl
          merge-multiple: true

      # Deploy documentation to GitHub Pages according to the mkdocs documentation
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force
